// Generated by CoffeeScript 1.4.0
(function() {
  var e, engine, getCommonHeaders, getCommonHeadersJs, view, __express, _ref;

  engine = require('./lib/engine').engine;

  _ref = require('./lib/view'), view = _ref.view, getCommonHeaders = _ref.getCommonHeaders, getCommonHeadersJs = _ref.getCommonHeadersJs;

  exports.engine = engine;

  exports.view = view;

  exports.getCommonHeaders = getCommonHeaders;

  exports.getCommonHeadersJs = getCommonHeadersJs;

  exports.expressEngine = e = new engine({
    verbose: false,
    prettyPrintErrors: true
  });

  exports.render = e.run;

  __express = exports.__express = function(filename, options, cb) {
    return e.run(filename, options, function(err, res) {
      if (err) {
        return cb(new Error(err));
      } else {
        return cb(null, res);
      }
    });
  };

  exports.__consolidate_engine_render = function(filename, options, cb) {
    var eng;
    if ((options.cache != null) && options.cache) {
      eng = e;
    } else {
      eng = new engine({
        verbose: false,
        prettyPrintErrors: true
      });
    }
    return eng.run(filename, options, function(err, res) {
      if (err) {
        return cb(new Error(err));
      } else {
        return cb(null, res);
      }
    });
  };

  exports.str_render = function(template_str, options, cb) {
    var err, res, v, _ref1;
    v = new view(template_str, options);
    _ref1 = v.run(options), err = _ref1[0], res = _ref1[1];
    return cb(err, res);
  };

  exports.compile = require('./lib/view').expressCompile;

}).call(this);
