// Generated by IcedCoffeeScript 1.3.3b
(function() {
  var engine, fs, getVersionNumber, printUsage, view;

  fs = require("fs");

  engine = require('../lib/engine').engine;

  view = require('../lib/view').view;

  printUsage = function() {
    console.log("  Usage: toffee [-c] input.toffee\n\n      -c == output to CoffeeScript (instead of JS)\n\n    TODO: make a more useful command line tool.");
    return process.exit(1);
  };

  getVersionNumber = function() {
    return JSON.parse(fs.readFileSync("" + __dirname + "/../package.json", "utf8")).version;
  };

  exports.run = function() {
    var args, coffee, e, fname, source, v;
    e = new engine();
    args = process.argv.slice(2);
    if (args.length === 2) {
      coffee = true;
      if (args[0] !== "-c") printUsage();
    } else if (args.length !== 1) {
      printUsage();
    }
    fname = args.slice(-1)[0];
    source = fs.readFileSync(fname, "utf8");
    v = new view(source);
    if (coffee) {
      return console.log(v._toCoffee());
    } else {
      return console.log(v._toJavaScript());
    }
  };

}).call(this);
