// Generated by CoffeeScript 1.3.3
(function() {
  var compile, fs, getCommonHeadersJs, getVersionNumber, path, program, recurseRun, run, view, _ref;

  fs = require('fs');

  path = require('path');

  _ref = require('../lib/view'), view = _ref.view, getCommonHeadersJs = _ref.getCommonHeadersJs;

  program = require('commander');

  getVersionNumber = function() {
    var o, p;
    p = fs.readFileSync("" + __dirname + "/../package.json", "utf8");
    o = JSON.parse(p);
    return o.version;
  };

  program.on('--help', function() {
    return console.log("\n  Examples:\n\n    toffee views               # recurses through views and builds views.js\n    toffee foo.toffee          # builds foo.js\n    toffee views -o templates  # builds templates.js\n    toffee -p foo.toffee       # outputs JS to stdout\n\n\n  Then use in your <html>:\n\n    <script src=\"views.js\"></script>\n    <script>\n       var pubvars   = { name: \"Hans Gruber\", criminal: true };\n       var some_html = toffee.render (\"views/layout.toffee\", pubvars);\n    </script>\n   ");
  });

  program.version(getVersionNumber()).option('-o, --output', 'output file').option('-p, --print', 'print output to stdout').option('-c, --coffee', 'output to CoffeeScript (not JS)').parse(process.argv);

  compile = function(start_path, path) {
    /*
      e.g., if start_path is /foo/bar
      and   path is /foo/bar/car/thing.toffee
    */

    var source, v;
    source = fs.readFileSync(path, 'utf8');
    v = new view(source, {
      fileName: path,
      bundlePath: path.slice(start_path.length),
      browserMode: true
    });
    return v._toJavaScript();
  };

  recurseRun = function(start_path, curr_path, out_text) {
    var file, files, stats, sub_path, sub_stats, _i, _len;
    stats = fs.statSync(curr_path);
    if (stats.isDirectory()) {
      files = fs.readdirSync(curr_path);
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        sub_path = path.normalize("" + curr_path + "/" + file);
        if (file.match(/\.toffee$/)) {
          out_text = recurseRun(start_path, sub_path, out_text);
        } else if (!(file === '.' || file === '..')) {
          sub_stats = fs.statSync(sub_path);
          if (sub_stats.isDirectory()) {
            out_text = recurseRun(start_path, sub_path, out_text);
          }
        }
      }
    } else {
      out_text += compile(start_path, curr_path);
    }
    return out_text;
  };

  run = exports.run = function() {
    var out_text, start_path;
    if (program.args.length !== 1) {
      console.log("Unexpected input. toffee --help for examples");
      return process.exit(1);
    } else {
      try {
        start_path = fs.realpathSync(program.args[0]);
      } catch (e) {
        console.log("Input file/path not found. toffee --help for examples");
        process.exit(1);
      }
      start_path = path.normalize(start_path);
      out_text = recurseRun(start_path, start_path, "");
      out_text = getCommonHeadersJs() + out_text;
      return console.log(out_text);
    }
  };

  if (require.main === module) {
    run();
  }

}).call(this);
