// Generated by CoffeeScript 1.12.2
(function() {
  exports.states = {
    TOFFEE: 1,
    COFFEE: 2
  };

  exports.TAB_SPACES = 2;

  exports.tweakables = {
    MISSING_FILE_RECHECK: 1000
  };

}).call(this);
