// Generated by CoffeeScript 1.12.2
(function() {
  var Pool;

  Pool = (function() {
    function Pool(cons, size) {
      this._consfn = cons;
      this._size = size;
      this._pool = [];
    }

    Pool.prototype.get = function() {
      if (this._pool.length > 0) {
        return this._pool.pop();
      } else {
        return this._consfn();
      }
    };

    Pool.prototype.release = function(x) {
      if (this._pool.length < this._size) {
        return this._pool.push(x);
      }
    };

    return Pool;

  })();

  exports.Pool = Pool;

}).call(this);
