// Generated by CoffeeScript 1.6.3
(function() {
  var lex, lexer;

  lexer = require('./coffee-script/lexer');

  lex = new lexer.Lexer();

  exports.interpolateString = function(str) {
    /*
    Similar to the interpolateString function in CoffeeScript,
    except that it doesn't actually work on anything inside an outer #{};
    we're just looking to recognize them.
    */

    var expr, i, inner, interpolated, letter, pi, res, tag, tokens, value, _i, _len, _ref;
    tokens = [];
    res = [];
    pi = 0;
    i = -1;
    while (letter = str.charAt(i += 1)) {
      if (letter === '\\') {
        i += 1;
        continue;
      }
      if (!(letter === '#' && str.charAt(i + 1) === '{' && (expr = lex.balancedString(str.slice(i + 1), '}')))) {
        continue;
      }
      if (pi < i) {
        tokens.push(['NEOSTRING', str.slice(pi, i)]);
      }
      inner = expr.slice(1, -1);
      if (inner.length) {
        tokens.push(['TOKENS', inner]);
      }
      i += expr.length;
      pi = i + 1;
    }
    if ((i > pi && pi < str.length)) {
      tokens.push(['NEOSTRING', str.slice(pi)]);
    }
    if (!tokens.length) {
      return res.push('STRING', '""');
    }
    if (tokens[0][0] !== 'NEOSTRING') {
      tokens.unshift(['', '']);
    }
    if (interpolated = tokens.length > 1) {
      res.push('(', '(');
    }
    for (i = _i = 0, _len = tokens.length; _i < _len; i = ++_i) {
      _ref = tokens[i], tag = _ref[0], value = _ref[1];
      if (i) {
        res.push('+', '+');
      }
      if (tag === 'TOKENS') {
        res.push([tag, value]);
      } else {
        res.push(['STRING', value]);
      }
    }
    if (interpolated) {
      res.push(')', ')');
    }
    return tokens;
  };

}).call(this);
