// Generated by IcedCoffeeScript 1.3.3a
(function() {
  var TAB_SPACES, coffee, parser, states, view, vm;

  parser = require('./cojo_lang').parser;

  coffee = require('coffee-script');

  states = require('./consts').states;

  vm = require('vm');

  TAB_SPACES = 2;

  view = (function() {

    function view(txt, options) {
      options = options || {};
      this.fileName = options.fileName || null;
      this.identifier = options.indentifier || "pub";
      this.codeObj = null;
      this.coffeeScript = null;
      this.javaScript = null;
      this.scriptObj = null;
      this.loadFromText(txt);
    }

    view.prototype.loadFromText = function(txt) {
      this.txt = txt;
      this.codeObj = parser.parse(txt);
      return this._cleanTabs();
    };

    view.prototype._cleanTabs = function() {
      var chunk, i, tab, _i, _len, _ref, _results;
      tab = this._tabAsSpaces();
      _ref = this.codeObj;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        chunk = _ref[i];
        if (chunk[0] === 'COFFEE') {
          _results.push(chunk[1] = chunk[1].replace(/\t/g, tab));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    view.prototype.run = function(options) {
      /*
          returns [err, str]
      */

      var err, res, sandbox, script;
      script = this._toScriptObj();
      err = null;
      try {
        sandbox = {
          __cojo_run_input: options
        };
        script.runInNewContext(sandbox);
        res = sandbox.__cojo_run_input.__cojo.res;
        delete sandbox.__cojo_run_input.__cojo;
      } catch (e) {
        err = "Error: " + e.message;
        err += "\nStack: " + e.stack;
      }
      return [err, res];
    };

    view.prototype._toScriptObj = function() {
      var d, txt;
      if (!(this.scriptObj != null)) {
        txt = this._toJavaScript();
        d = Date.now();
        this.scriptObj = vm.createScript(txt);
        console.log("Compiled to ScriptObj in " + (Date.now() - d) + "ms");
      }
      return this.scriptObj;
    };

    view.prototype._toJavaScript = function() {
      var c, d;
      if (!(this.javaScript != null)) {
        c = this._toCoffee();
        d = Date.now();
        this.javaScript = coffee.compile(c, {
          bare: false
        });
        console.log("Compiled to JavaScript in " + (Date.now() - d) + "ms");
      }
      return this.javaScript;
    };

    view.prototype._toCoffee = function() {
      var d, res;
      if (!(this.coffeeScript != null)) {
        d = Date.now();
        res = this._coffeeHeaders();
        res += this._toCoffeeRecurse(this.codeObj, TAB_SPACES, 0)[0];
        res += this._coffeeFooters();
        this.coffeeScript = res;
        console.log("Compiled to CoffeeScript in " + (Date.now() - d) + "ms");
      }
      return this.coffeeScript;
    };

    view.prototype._toCoffeeRecurse = function(obj, indent_level, indent_baseline) {
      var delta, i_delta, item, res, s, temp_indent_level, zone_baseline, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      res = "";
      i_delta = 0;
      switch (obj[0]) {
        case "INDENTED_COJO_ZONE":
          indent_level += TAB_SPACES;
          _ref = obj[1];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            _ref1 = this._toCoffeeRecurse(item, indent_level, indent_baseline), s = _ref1[0], delta = _ref1[1];
            res += s;
          }
          break;
        case "COJO_ZONE":
          res += "\n" + (this._space(indent_level)) + "__cojo.state = states.COJO";
          _ref2 = obj[1];
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            item = _ref2[_j];
            _ref3 = this._toCoffeeRecurse(item, indent_level, indent_baseline), s = _ref3[0], delta = _ref3[1];
            res += s;
          }
          break;
        case "COFFEE_ZONE":
          res += "\n" + (this._space(indent_level)) + "__cojo.state = states.COFFEE";
          zone_baseline = this._getZoneBaseline(obj[1]);
          temp_indent_level = indent_level;
          _ref4 = obj[1];
          for (_k = 0, _len2 = _ref4.length; _k < _len2; _k++) {
            item = _ref4[_k];
            _ref5 = this._toCoffeeRecurse(item, temp_indent_level, zone_baseline), s = _ref5[0], delta = _ref5[1];
            res += s;
            temp_indent_level = indent_level + delta;
          }
          break;
        case "COJO":
          res += "\n" + (this._space(indent_level)) + "__cojo.state = states.COJO";
          res += ("\n" + (this._space(indent_level)) + "__cojo.out.push ") + '"""' + this._escapeForStr(obj[1]) + '"""';
          res += "\n" + (this._space(indent_level)) + "__cojo.state = states.COFFEE";
          break;
        case "COFFEE":
          res += "" + (this._space(indent_level)) + "# DEBUG: indent_level=" + indent_level + " indent_baseline=" + indent_baseline;
          res += "\n" + (this._reindent(obj[1], indent_level, indent_baseline));
          i_delta = this._getIndentationDelta(obj[1], indent_baseline);
          break;
        default:
          throw "Bad parsing. " + obj + " not handled.";
          return ["", 0];
      }
      return [res, i_delta];
    };

    view.prototype._escapeForStr = function(s) {
      /*
          escapes a string so it can make it into coffeescript
          triple quotes without losing whitespace, etc.
      */
      s = s.replace(/\n/g, '\\n');
      s = s.replace(/\t/g, '\\t');
      return s;
    };

    view.prototype._getZoneBaseline = function(obj_arr) {
      var ib, obj, _i, _len;
      for (_i = 0, _len = obj_arr.length; _i < _len; _i++) {
        obj = obj_arr[_i];
        if (obj[0] === "COFFEE") {
          ib = this._getIndentationBaseline(obj[1]);
          if (ib != null) return ib;
        }
      }
      return 0;
    };

    view.prototype._getIndentationBaseline = function(coffee) {
      var line, lines, _i, _len;
      lines = coffee.split("\n");
      if (lines.length === 0) return null;
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        if (!line.match(/^[\W]*$/)) return line.match(/[\W]*/)[0].length;
      }
      return null;
    };

    view.prototype._getIndentationDelta = function(coffee, baseline) {
      /*
          given an arbitrarily indented set of coffeescript, returns the delta
          between the first and last lines, in chars.
          Ignores leading/trailing whitespace lines
          If passed a baseline, uses that instead of own.
      */

      var lines, res, y, y_l;
      if (!(baseline != null)) baseline = this._getIndentationBaseline(coffee);
      if (!(baseline != null)) {
        res = 0;
      } else {
        lines = coffee.split("\n");
        while (lines.length && lines[lines.length - 1].match(/^[\W]*$/)) {
          lines.pop();
        }
        if (lines.length < 1) {
          res = 0;
        } else {
          y = lines[lines.length - 1];
          y_l = y.match(/[\W]*/)[0].length;
          res = y_l - baseline;
        }
      }
      return res;
    };

    view.prototype._reindent = function(coffee, indent_level, indent_baseline) {
      var indent, line, lines, res, rxx, strip;
      lines = coffee.split('\n');
      while (lines.length && lines[0].match(/^[\W]*$/)) {
        lines = lines.slice(1);
      }
      if (!lines.length) return '';
      rxx = /^[\W]*/;
      strip = indent_baseline;
      indent = this._space(indent_level);
      res = ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = lines.length; _i < _len; _i++) {
          line = lines[_i];
          _results.push("" + indent + line.slice(strip));
        }
        return _results;
      })()).join("\n");
      return res;
    };

    view.prototype._space = function(indent) {
      var i;
      return ((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= indent ? _i < indent : _i > indent; i = 0 <= indent ? ++_i : --_i) {
          _results.push(" ");
        }
        return _results;
      })()).join("");
    };

    view.prototype._tabAsSpaces = function() {
      var i;
      return ((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= TAB_SPACES ? _i < TAB_SPACES : _i > TAB_SPACES; i = 0 <= TAB_SPACES ? ++_i : --_i) {
          _results.push(" ");
        }
        return _results;
      })()).join("");
    };

    view.prototype._coffeeHeaders = function() {
      var header, tab;
      tab = this._tabAsSpaces();
      header = "domain                = this\ndomain.cojoTemplates  = domain.cojoTemplates or {}\ndomain.cojoTemplates[\"" + this.identifier + "\"] = (locals) ->\n" + tab + "domain                = this\n" + tab + "locals.__cojo         = {}\n" + tab + "`with (locals) {`\n" + tab + "__cojo.out = []\n" + tab + "states = " + (JSON.stringify(states)) + "\n" + tab + "if not include? then include = (fname, vars) -> \n" + tab;
      return header;
    };

    view.prototype._coffeeFooters = function() {
      var footer, tab;
      tab = this._tabAsSpaces();
      footer = "\n\n" + tab + "__cojo.res = __cojo.out.join \"\"\n" + tab + "return __cojo.res\n" + tab + "`} /* closing JS 'with' */ `\n# sometimes we want to execute the whole thing in a sandbox\n# and just output results\nif __cojo_run_input?\n" + tab + "return domain.cojoTemplates[\"" + this.identifier + "\"] __cojo_run_input";
      return footer;
    };

    return view;

  })();

  exports.view = view;

  exports.expressCompile = function(txt, options) {
    var v;
    v = new view(txt, options);
    return function(vars) {
      var res;
      res = v.run(vars);
      return console.log(res[1]);
    };
  };

}).call(this);
